## ---- create-plot-labels

labels.challenges <- c(C01 = 'C01 = Broad scope', 
                       C02 = 'C02 = Unclear expectations', 
                       C03 = 'C03 = Competing needs', 
                       C04 = 'C04 = Language or custom differences', 
                       C05 = 'C05 = Difficult co-creator relationships', 
                       C06 = 'C06 = Poor planning of collaboration', 
                       C07 = 'C07 = Limited exchange', 
                       C08 = 'C08 = Unequal participation opportunities', 
                       C09 = 'C09 = Resource constraints', 
                       C10 = 'C10 = Lack of diverse perspectives', 
                       C11 = 'C11 = Difficulties recruiting co-creators', 
                       C12 = 'C12 = Difficulties in finding support', 
                       C13 = 'C13 = Turnover', 
                       C15 = 'C15 = Potential harm to co-creators',
                       C16 = 'C16 = Failure to acknowledge', 
                       C17 = 'C17 = Mistrust', 
                       C18 = 'C18 = Skills or knowledge gap',
                       C19 = 'C19 = Difficulties distributing workload', 
                       C20 = 'C20 = Limited flexibility or adaptiveness', 
                       C21 = 'C21 = Lack of a prototype', 
                       C22 = 'C22 = Other')

labels.facilitators <- c(F01 = 'F01 = Institutional support', 
                         F02 = 'F02 = Seek guidance', 
                         F03 = 'F03 = Co-creator exchanges', 
                         F04 = 'F04 = Tailored spaces', 
                         F05 = 'F05 = Orientation', 
                         F06 = 'F06 = Training', 
                         F07 = 'F07 = Continuous involvement', 
                         F08 = 'F08 = Leverage strengths', 
                         F09 = 'F09 = Delegate research tasks', 
                         F10 = 'F10 = Adaptive process', 
                         F11 = 'F11 = Transparent communication', 
                         F12 = 'F12 = Needs analysis', 
                         F13 = 'F13 = Ownership', 
                         F14 = 'F14 = Acknowledging co-creators',
                         F15 = 'F15 = Broad recruitment', 
                         F16 = 'F16 = Targeted recruitment', 
                         F17 = 'F17 = Facilitation strategies',
                         F18 = 'F18 = Documentation', 
                         F19 = 'F19 = Conflict management', 
                         F20 = 'F20 = Feasible design', 
                         F21 = 'F21 = Trust and dependability', 
                         F22 = 'F22 = Prior relationship', 
                         F23 = 'F23 = Prototype or demo', 
                         F24 = 'F24 = Top-down management', 
                         F25 = 'F25 = Other')